/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * fig.java
 *
 * Created on Aug 19, 2002, 11:16:14 PM
 */

/**
 *
 * @author g1.test1
 */import java.applet.*;
 import java.awt.*;
 public class fig extends java.applet.Applet {
  public void paint(Graphics a)
     {
      int arr1[]={40,80,40};
      int arr2[]={50,0,50};
      a.draw3DRect(10, 20, 530, 140, true);
  }
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
