/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * flag.java
 *
 * Created on Aug 19, 2002, 10:22:14 PM
 */

/**
 *
 * @author g1.test1
 */
 import java.applet.*;
 import java.awt.*;
public class flag extends java.applet.Applet {
public void Paint(Graphics g)
    {
    /*g.setColor(Color.orange);
    g.fillRect(10, 10, 100, 40);
    g.setColor(Color.white);
    g.fillRect(10, 40, 100, 40);
    g.setColor(Color.green);
    g.fillRect(10, 80, 100, 40);
    g.setColor(Color.blue);
    */
    g.drawRect(20, 30, 100, 179);
}
    
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("jLabel1");
        add(jLabel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
