/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * font.java
 *
 * Created on Aug 19, 2002, 10:52:51 PM
 */

/**
 *
 * @author g1.test1
 */import java.applet.*;
 import java.awt.*;
public class font extends java.applet.Applet {

String msg="my new applet";
private Font font;
    public void paint(Graphics g)
    {font =new Font("Helvetica",Font.BOLD,48);
    g.setColor(Color.pink);
    g.fillOval(10, 10, 330, 100);
    g.setColor(Color.red);
    g.drawOval(10, 10, 330, 100);
    g.drawOval(9, 9, 332, 102);
    g.drawOval(8, 8, 334, 104);
    g.drawOval(7, 7, 336, 106);
    g.setColor(Color.black);
    g.setFont(font);
    g.drawString(msg, 40, 75);
    }
    
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
