/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * light.java
 *
 * Created on Aug 19, 2002, 10:08:05 PM
 */

/**
 *
 * @author g1.test1
 */import java.applet.*;
 import java.awt.*;
public class light extends java.applet.Applet {
public void paint(Graphics a)
    {

    a.setColor(Color.black);
    a.fillRect(50, 20, 100, 250);
    a.setColor(Color.red);
    a.fillOval(75,30 , 50, 50);
    a.setColor(Color.yellow);
      a.fillOval(75,85 , 50, 50);
      a.setColor(Color.green);
      a.fillOval(75,140 , 50, 50);
}
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
