/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * newdraw.java
 *
 * Created on Aug 19, 2002, 9:57:05 PM
 */

/**
 *
 * @author g1.test1
 */
import java.applet.Applet.*;
import java.awt.*;
public class newdraw extends java.applet.Applet {

    public void paint(Graphics g)
    {
        int val=10;
        int val1=20;
        int sum=val+val1;
        String s=String.valueOf(sum);
        g.drawString(s, 100,100);
    }
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
